Feature hello world
AnelisaDee/Hello-World pull request #1
Opened 2022-08-16 18:28 UTC by AnelisaDee

First repo at Microverse

2022-08-16 21:25 UTC, codecaiine requested changes
Hi @AnelisaDee , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Project is professional :heavy_check_mark: 
- Good use of Github flow :heavy_check_mark: 
- No linters errors :heavy_check_mark: 
- Great commits messages :heavy_check_mark: 

## Required Changes ♻️

- [ ] Please edit your Pull Request to make it a more descriptive t, it should tell what changes are inside to the reviewer . A good example will be **Set up a Hello Microverse project** instead of  **First project feature**  :+1: 
- [ ] Please edit also your Pull Request summary because like your PR title the summary should describe introduced changes in more detail. :+1: 
You can check the example below :arrow_down: 
![Screenshot from 2022-08-16 18-25-08](https://user-images.githubusercontent.com/6615394/184951982-6f947437-2d41-415c-b6d7-b26ae0855ea3.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 21:25 UTC, codecaiine commented on .gitignore
> +test.md
- [ ]  Please add the `node_modules` directory to the .gitignore file. It's a good practice to add the node_modules to the .gitignore. It will help you to avoid a big size of dependencies in your repository. :smile:

2022-08-16 21:25 UTC, codecaiine commented on README.md
> +NOTE: we recommend using the MIT license - you can set it up quickly by using templates available on GitHub. You can also use any other license if you wish.
- [ ] Please add a descriptive README file to your project by using [this template](https://github.com/microverseinc/readme-template) provide by microverse and please customize it to your project because it is important to keep your project profession :smile: 
- [ ] Please don't forget to add a license to your project and I recommend using the [MIT license](https://choosealicense.com/licenses/mit/), Set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository). another resource is [any other license](https://choosealicense.com/licenses/) . :smile:

2022-08-17 20:03 UTC, AnelisaDee commented on .gitignore
> +test.md
Good day, thank you for the positive feedback and suggested changes that I need to apply. I will try to add the node_modules  in the .gitignore as soon as I can. Thanks :)

2022-08-17 20:58 UTC, codecaiine commented on .gitignore
> +test.md
hi @AnelisaDee  It is my pleasure and don't hesitate to tag me or slack me if you need any help :+1:

2022-08-17 23:38 UTC, AnelisaDee commented on .gitignore
> +test.md
Hi @codecaiine I finally managed to make changes according to your suggestions. Please review all my changes, your feedback would be highly appreciated. Thanks :)

2022-08-18 14:43 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @AnelisaDee 

Your project is complete! Great job for making the requested changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Validations correctly implemented
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 14:44 UTC, merged